### ISSUE TITLE
Velocity display in mph

### ISSUE THREAD

**Issue by Matley-dev** [OpenGIS/inreach-mapshare#11]
Thank you for a great resource.

A small issue I have noticed. The More detail option for a point shows the velocity. In kph it is correct but when converting to mph you have multiplied the kph by 1.690344 rather than dividing it. 

This appears in assets/js/shortcode.js & assets/js/shortcode.min.js

Update - I just tried version 2 and got the same, but different files affected dist/inreach-mapshare.js & src/js/shortcode.js

**Comment by morehawes** [comment]
Hi @Matley-dev,

Thanks for bringing this to my attention. I have fixed this in the latest release (v2.0.1).

Cheers,

Joe
