### ISSUE TITLE
No donation option

### ISSUE THREAD

**Issue by yeti08** [OpenGIS/inreach-mapshare#3]
I have been trying to do something like this for 3 years to share hikes with others better than the clunky Garmin site, and this plugin works perfectly!  I would gladly donate to the effort, but don't see a donation link here or in the plugin.  If you don't accept donations, thank you for the amazing work!

**Comment by morehawes** [comment]
@yeti08,

Sometimes you get an email that makes your week.. sometimes your *month*. You gave me the kick I needed!

Please donate to your favourite cause. Your money is no good here ❤️

[Joe](https://www.youtube.com/watch?v=c3sOuEv0E2I)
