### ISSUE TITLE
How does one install the plugin?

### ISSUE THREAD

**Issue by mmcc-xx** [OpenGIS/inreach-mapshare#4]
Apologies in advance if this is a really dumb question....

I am pretty new to wordpress. How do I install this plugin? It doesn't show up with I search for plugins to install, and I'm not sure what I would upload.

**Comment by mmcc-xx** [comment]
As is often the case, I figured it out immediately after asking the question. For anyone else: There's a zip file in the repo. Download it, and then upload it to wordpress.

**Comment by morehawes** [comment]
Thanks @mmcc-xx, I will be sure to improve the documentation to mention this.

Joe

**Comment by morehawes** [comment]
@mmcc-xx,

I have updated the project readme with improved installation instructions. Thanks again for reaching out and please do let me know if anything else is unclear.

Cheers,

Joe
